name: Linting

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["check-enums"]
    types: [completed]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure
